baseURL = 'https://danilosantos.info'
languageCode = 'pt-br'
title = 'Danilo Santos'
description = "Publicações sobre desenvolvimento e tecnologia."
theme = 'hello-friend-ng'

defaultContentLanguage = 'pt-br'
defaultContentLanguageInSubdir = true

[params]
  [params.logo]
    logoMark     = ">"
    logoText     = "$ echo 'Olá Mundo!'"
    logoHomeLink = "/"
    logoCursorColor    = "#00ff04"

  [params.portrait]
    path     = "/img/photo-blog.jpg"
    alt      = "Portrait"
    maxWidth = "200px"


[languages]
  [languages.pt-br]
    contentDir = 'content/pt-br'
    disabled = false
    languageCode = 'pt-BR'
    languageName = 'Pt-Br'
    weight = 1
    [languages.pt-br.menus]
      [[languages.pt-br.menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 1
      [[languages.pt-br.menus.main]]
        name = 'Sobre'
        pageRef = '/about'
        weight = 2
    [languages.pt-br.params]
  [languages.us]
    contentDir = 'content/us'
    disabled = false
    languageCode = 'us'
    languageDirection = 'ltr'
    languageName = 'En'
    title = 'Danilo Santos'
    weight = 2
    [languages.us.menus]
      [[languages.us.menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 1
      [[languages.us.menus.main]]
        name = 'About'
        pageRef = '/about'
        weight = 2
    [languages.us.params]
      subtitle = 'Data'
      [languages.us.params.logo]
        logoText = "$ echo 'Hello World!'"