baseURL = 'https://danilosantos.info'
languageCode = 'pt-br'
title = 'Danilo Santos'
description = "Publicações sobre desenvolvimento e tecnologia."
theme = 'hello-friend-ng'


defaultContentLanguage = 'pt-br'
defaultContentLanguageInSubdir = true
enableGlobalLanguageMenu = true
enableMissingTranslationPlaceholders = true

[params]
  [params.logo]
    logoMark     = ">"
    logoText     = "$ echo 'Olá Mundo!'"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#00ff04"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText 
    # logoCursorPathname = true

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Addon: Startpage portrait 
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Uncomment this if you want a portrait on your start page

  [params.portrait]
    path     = "/img/photo-blog.jpg"
    alt      = "Portrait"
    maxWidth = "200px"

[languages]
  [languages.pt-br]
    contentDir = 'content/pt-br'
    disabled = false
    languageCode = 'pt-BR'
    languageName = 'Pt-Br'
    title = 'Danilo Santos'
    weight = 1
    [languages.pt-br.menus]
      [[languages.pt-br.menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 1
      [[languages.pt-br.menus.main]]
        name = 'Sobre'
        pageRef = '/about'
        weight = 2
    [languages.pt-br.params]
      subtitle = 'Dados'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'En'
    title = 'Danilo Santos'
    description = "Publications on development and technology."
    weight = 2
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 1
      [[languages.en.menus.main]]
        name = 'About'
        pageRef = '/about'
        weight = 2
    [languages.en.params]
      subtitle = 'Data'
      [languages.en.params.logo]
        logoText = "$ echo 'Hello World!'"
