baseURL = 'https://danilosantos.info'
languageCode = 'pt-br'
title = 'Danilo Santos'
description = "Engenharia de Software | Automação | Inteligência de Negócios."
theme = 'hello-friend-ng'

defaultContentLanguage = 'pt-br'
defaultContentLanguageInSubdir = true

[services]
  [services.googleAnalytics]
    ID = 'G-526ZBV00C7'

[params]
  enableThemeToggle = true
  [params.logo]
    logoMark     = ">"
    logoText     = "danilosantos~$"
    logoHomeLink = "/"
    logoCursorColor    = "#00ff04"

  [params.portrait]
    path     = "/img/photo-blog.jpg"
    alt      = "Portrait"
    maxWidth = "200px"

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Addon: Social icons
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #
  [[params.social]]
    name = "github"
    url  = "https://github.com/dssantos/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/danilo-da-silva-santos/"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/12758107/danilo-santos/"

  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/@danilosantos1986/"

[languages]
  [languages.pt-br]
    contentDir = 'content/pt-br'
    disabled = false
    languageCode = 'pt-BR'
    languageName = 'Pt-Br'
    weight = 1
    [languages.pt-br.menus]
      [[languages.pt-br.menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 1
      [[languages.pt-br.menus.main]]
        name = 'Sobre'
        pageRef = '/about'
        weight = 2
    [languages.pt-br.params]
      homeSubtitle = "Engenharia de Software | Automação | Inteligência de Negócios"
  [languages.en-us]
    contentDir = 'content/en-us'
    disabled = false
    languageCode = 'en-us'
    languageDirection = 'ltr'
    languageName = 'En'
    title = 'Danilo Santos'
    weight = 2
    [languages.en-us.menus]
      [[languages.en-us.menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 1
      [[languages.en-us.menus.main]]
        name = 'About'
        pageRef = '/about'
        weight = 2
    [languages.en-us.params]
      homeSubtitle = "Software Engineering | Automation | Business Intelligence"