baseURL = 'https://danilosantos.info'
languageCode = 'pt-br'
title = 'Danilo Santos'
description = "Publicações sobre desenvolvimento e tecnologia."
theme = 'hello-friend-ng'

defaultContentLanguage = 'pt-br'

[params]
  [params.logo]
    logoMark     = ">"
    logoText     = "$ echo 'Olá Mundo!'"
    logoHomeLink = "/"
    logoCursorColor    = "#00ff04"

  [params.portrait]
    path     = "/img/photo-blog.jpg"
    alt      = "Portrait"
    maxWidth = "200px"


[languages]
  [languages.pt-br]
    contentDir = 'content/pt-br'
    disabled = false
    languageCode = 'pt-BR'
    weight = 1
    [languages.pt-br.menus]
      [[languages.pt-br.menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 1